---
name: Unit tests

on: [push, pull_request]

jobs:
  Python36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Get Docker image
        run: docker pull suoto/hdl_checker_test:latest
      - name: Run tests
        run: ./run_tests.sh -e py36-linux -- -v
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
  Python37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Get Docker image
        run: docker pull suoto/hdl_checker_test:latest
      - name: Run tests
        run: ./run_tests.sh -e py37-linux -- -v
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
  Python38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Get Docker image
        run: docker pull suoto/hdl_checker_test:latest
      - name: Run tests
        run: ./run_tests.sh -e py38-linux -- -v
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)

  Pypi:
    runs-on: ubuntu-latest
    needs: [Python36, Python37, Python38]
    steps:
      - uses: actions/checkout@v1
      - name: Build dist
        run: python setup.py sdist
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
